### A rank 1 ndarray

In [1]:
import numpy as np

rank_1 = np.array([2 ,22,123])  # Creating a rank 1 array

print(type(rank_1))     # The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


#### shape of the array, it should have just one dimension (Rank 1)


In [2]:
print(rank_1.shape)

(3,)


#### because this is a 1-rank array, we need only one index to accesss each element


In [3]:
print(rank_1[0], rank_1[1], rank_1[2]) 

2 22 123


#### ndarrays are mutable, here change an element of the array

In [4]:
rank_1[0] = 888            

print(rank_1)

[888  22 123]


### A rank 2 ndarray

In [5]:
rank_2 = np.array([[11,12,13],
                   [21,22,23]])   # Create a rank 2 array

print(rank_2)  # print the array
print()
print(f"The shape is {rank_2.shape[0]} rows and {rank_2.shape[1]} columns ".format(rank_2.shape))  # rows x columns                   


[[11 12 13]
 [21 22 23]]

The shape is 2 rows and 3 columns 


#### many ways to create numpy arrays

#### create a 3x3 array of zeros


In [6]:
import numpy as np

example_1 = np.zeros((3, 3))      
example_1                  

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### create a 3x3 array filled with 6.0


In [7]:
example_2 = np.ones((3,3))
example_2


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
example_3 = np.full((3,3), 6)
example_3

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

#### create a 3x3 matrix with the diagonal 1s and the others 0


In [9]:
example_4 = np.eye(3,3)
example_4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### create an array of random numbers in between 0 to 1

In [11]:
example_5 = np.random.random((4,4))
example_5

array([[0.95954491, 0.80352393, 0.39768564, 0.69410722],
       [0.21507377, 0.65692485, 0.79685868, 0.8968704 ],
       [0.02376188, 0.64883526, 0.78355708, 0.80762737],
       [0.47827425, 0.95442673, 0.86559899, 0.32762471]])

In [12]:
example_6 = np.random.randint(0, 10)
print("Random number between 0 and 10 is % s" % (example_6))

Random number between 0 and 10 is 2


In [13]:
import numpy as np

# Rank 2 array of shape (3, 4)
array_1 = np.array([[11,12,13,14],
                    [21,22,23,24],
                    [31,32,33,34]])
array_1

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [14]:
array_1[::,1:3]

array([[12, 13],
       [22, 23],
       [32, 33]])

#### slicing of last column

In [15]:
array_1[::,-1]

array([14, 24, 34])

In [16]:
array_1[::,1:2]

array([[12],
       [22],
       [32]])

In [17]:
array_1[::,1:2].shape

(3, 1)

In [18]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = array_1[0, :]    # Rank 1 view 

print(row_rank1, row_rank1.shape)  # notice only a single []

[11 12 13 14] (4,)


In [19]:
# Slicing alone: generates an array of the same rank as an_array

row_rank1 = array_1[1:2, :]    # Rank 1 view 

print(row_rank1, row_rank1.shape)  # notice  [[]]

[[21 22 23 24]] (1, 4)


In [20]:
#We can do the same thing for columns of an array:

print()
col_rank1 = array_1[:, 1]
col_rank2 = array_1[:, 1:2]
col_rank3 = array_1[::, 3:4]
col_rank4 = array_1[:, 3]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2
print()
print(col_rank3,col_rank3.shape)
print()
print(col_rank4,col_rank4.shape)


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)

[[14]
 [24]
 [34]] (3, 1)

[14 24 34] (3,)


In [21]:
# Create a new array
array_2 = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(array_2)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [22]:
## Create an array of indices
col_indices = np.array([0, 2, 1, 2])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 2 1 2]

Rows indices picked :  [0 1 2 3]


In [23]:
# pairings of row and column indices
for row, col in zip(row_indices, col_indices):
    print(row,col)

0 0
1 2
2 1
3 2


In [24]:
# Select one element from each row
print('Values in the array at those indices: ',array_2[row_indices, col_indices])

Values in the array at those indices:  [11 23 32 43]


In [25]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (array_2 > 25)
filter

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [26]:
# we can now select just those elements which meet that criteria
print(array_2[filter])

[31 32 33 41 42 43]


In [27]:
# For short, we could have just used the approach below without the need for the separate filter array.

array_2[(array_2 % 2 == 0)]

array([12, 22, 32, 42])

### Data types

In [28]:
example1 = np.array([11, 22, 33], dtype=np.int64) #You can also tell Python the  data type
print(example1.dtype)

int64


#### you can use this to force floats into integers (using floor function)


In [29]:
example2 = np.array([121.6,142.3], dtype=np.int64)
print(example2.dtype)
print()
print(example2)

int64

[121 142]


In [30]:
example3 = np.array([11, 22, 33], dtype=np.float64) #You can also tell Python the  data type
print(example3.dtype)
print(example3)

float64
[11. 22. 33.]


### Arithmatic array operations

In [31]:
x = np.array([[11,12],[13,14]], dtype=np.int)
y = np.array([[20.4, 22.5],[32.6,64.7]], dtype=np.float64)

In [32]:
x

array([[11, 12],
       [13, 14]])

In [33]:
y

array([[20.4, 22.5],
       [32.6, 64.7]])

In [34]:
x+y

array([[31.4, 34.5],
       [45.6, 78.7]])

In [35]:
np.add(x,y)

array([[31.4, 34.5],
       [45.6, 78.7]])

In [36]:
np.subtract(x,y)

array([[ -9.4, -10.5],
       [-19.6, -50.7]])

In [37]:
np.multiply(x,y)

array([[224.4, 270. ],
       [423.8, 905.8]])

In [38]:
np.divide(x, y)

array([[0.53921569, 0.53333333],
       [0.39877301, 0.21638331]])

In [39]:
np.sqrt(x)

array([[3.31662479, 3.46410162],
       [3.60555128, 3.74165739]])

In [40]:
np.exp(x)

array([[  59874.1417152 ,  162754.791419  ],
       [ 442413.39200892, 1202604.28416478]])

#### Basic Statistical operations

In [41]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[ -5.25477432 -11.73838651 -10.44230336 -13.97724543  14.16064243]
 [ -1.89878021 -15.53929693  -4.74954222  16.00700351  -7.69624809]]


In [42]:
arr.mean()

-4.112893112776216

In [43]:
arr.mean(axis =1)

array([-5.45041344, -2.77537279])

In [44]:
arr.mean(axis =0)

array([ -3.57677727, -13.63884172,  -7.59592279,   1.01487904,
         3.23219717])

In [45]:
arr.sum()

-41.12893112776216

In [46]:
np.median(arr)

-6.475511204895765

In [47]:
np.median(arr, axis = 1)

array([-10.44230336,  -4.74954222])

In [48]:
sorting = np.median(arr, axis=0)

In [49]:
sorting

array([ -3.57677727, -13.63884172,  -7.59592279,   1.01487904,
         3.23219717])

In [50]:
sorting.sort()

In [51]:
sorting

array([-13.63884172,  -7.59592279,  -3.57677727,   1.01487904,
         3.23219717])

#### Set Operations with np.array data type:

In [52]:
train = np.array(['mobile','price','clip'])
test = np.array(['lamp','mobile','clip'])
print(train, test)

['mobile' 'price' 'clip'] ['lamp' 'mobile' 'clip']


#### intersection

In [53]:
np.intersect1d(train,test)

array(['clip', 'mobile'], dtype='<U6')

In [54]:
np.union1d(train, test)

array(['clip', 'lamp', 'mobile', 'price'], dtype='<U6')

In [55]:
print( np.setdiff1d(train, test) )# elements in train that are not in test


['price']


In [56]:
print( np.in1d(train, test) )# element of train is also prsent in test

[ True False  True]


### conversion of files

#### npy file

In [57]:
convertTo_npy = np.array([1,2,3,4])
convertTo_npy

array([1, 2, 3, 4])

In [58]:
np.save('npy_file',convertTo_npy)

In [59]:
np.load('npy_file.npy')

array([1, 2, 3, 4])

#### txt file

In [60]:
np.savetxt('test_file.txt',X = convertTo_npy, delimiter=',')

In [61]:
np.loadtxt('test_file.txt',delimiter=',')

array([1., 2., 3., 4.])

In [62]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

In [63]:
mat = np.random.rand(5,5)
mat

array([[0.33201286, 0.27868654, 0.53684459, 0.39799888, 0.74136065],
       [0.12550335, 0.21931415, 0.02358412, 0.55697765, 0.2365765 ],
       [0.38125725, 0.65974841, 0.77622491, 0.37733689, 0.57566076],
       [0.81216276, 0.38440085, 0.07808294, 0.13797307, 0.55313413],
       [0.19550578, 0.41251515, 0.94631334, 0.38146601, 0.0569606 ]])

In [64]:
np.where( mat > 0.5 , 1000, 1.5)

array([[   1.5,    1.5, 1000. ,    1.5, 1000. ],
       [   1.5,    1.5,    1.5, 1000. ,    1.5],
       [   1.5, 1000. , 1000. ,    1.5, 1000. ],
       [1000. ,    1.5,    1.5,    1.5, 1000. ],
       [   1.5,    1.5, 1000. ,    1.5,    1.5]])

In [65]:
Y = np.random.normal(size = (1,5))
print(Y)
#print(Y.dtype)
print(Y.shape)
print()
z = np.random.normal(size = (1,5))[0]
print(z)
#print(z.dtype)
print(z.shape)


[[ 0.02766818  0.24269704  2.31008629 -0.30250159  1.77847859]]
(1, 5)

[ 0.2439223   0.09973545  0.0903217  -0.92192997 -0.49827613]
(5,)


In [66]:
Z = np.random.randint(low = 2, high = 50, size = 4)
print(Z)

[44 26 10 36]


In [67]:
np.random.permutation(Z) #return a new ordering of elements in Z

array([26, 44, 36, 10])

#### uniform distribution

In [68]:
np.random.uniform(size=4) #uniform distribution

array([0.45439604, 0.12957771, 0.90688029, 0.83100002])

#### Normal Distribution

In [69]:
np.random.normal(size=4) #normal distribution

array([-0.1103473 , -0.78138894,  0.24450623,  1.06470642])

#### Merging Dataset

In [70]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[20 14]
 [26 17]]

[[ 4 28]
 [18 32]]


#### vertically merging data

In [71]:
np.vstack((K,M))

array([[20, 14],
       [26, 17],
       [ 4, 28],
       [18, 32]])

In [72]:
np.concatenate([K, M], axis = 0)

array([[20, 14],
       [26, 17],
       [ 4, 28],
       [18, 32]])

#### Horizontally merging datset

In [73]:
np.hstack((K,M))

array([[20, 14,  4, 28],
       [26, 17, 18, 32]])

In [74]:
np.concatenate([K, M], axis =1)

array([[20, 14,  4, 28],
       [26, 17, 18, 32]])